load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "port",
    srcs = ["fruit.go"],
    importpath = "github.com/defmsy/labs-golang/lab-bazel-getting-started/internal/core/port",
    visibility = ["//visibility:public"],
)
